//
// Created by Kyle on 15.06.24.
//

#ifndef BANNER_H
#define BANNER_H

#include <string>
#include <vector>

// Include the text file content
const std::string fileContent = R"(
'. ...,,;c;,;;,,,,:ldocldddxxOOkOOkxkxxkOkllddoxOOOOdcoxkkkxolclclx0Okxl::ccokkOkdooclxdddddxlcxkkxxl:c:coddddoolllodlc::;;;;;,,'....,'.  ... ..;''ll,
:'....''','':;,:l::clodxkxdddddddxxxkkkxkOkxdoooxOOkkoldxkkxdoccc:oxkkkl:cccdkxxxolccldxddddlldxxxxlccldxkkxxdlcccc::;;;,;;;::;,'.',,,;,'.....''...''.
o:,:cldxdxxxkkkkkxddkOOkkkxxkkkkxddooddxkkO00kolllodxOdclloxxdl;.':odod:',,;ldodl,'';clddc::cdkxdolccoxkkkxolccc:;;;;;,,''''',,''.....',,''''',,'',,,'
kOkOOk0OkkkxxxxdoloxxddddooddddodddkOkddoodkO0Kkl;;loxkl. .lo:,',:c;..,;,,;:;,.',;lc,';lc. .codoc,,ldxxdolc:cccc:;,'..',:;,........................''.
0koloxkdl:,'',::cdOOOkxkkxxdddxddooodkkkdlcldodOx,.:dkd:'.'::'..;ll;..,;lkxl:'.',:c,. .;,..',,::'.'oxdl:;;:cc:;,'......,cdo;....'....      ....   .''.
Oo'.';::;';::coloxkxxxddddxdoddkOkdoolldxxdl,.:l:,,cxkxo,':::'  .:lc'.;:'.,::'.':c:.  .;;;',,.''....,;..,lc,'..........'ck0d,..........  ...       ...
dolllllddoodddldxxxxxxdddddoodooodxxkol;,loc;';c,...cxol:';cc,  .;c:''::. .;:;',::;.  ':;;,;'.',,. .,,..,;..............;xK0l.........     ...........
kkxddooolc:;::cddddoodddddooodddoddoclc,..,;:,;l:.  'c;;:',lo;   .;:;,cc. 'c:;,;;..'..,cc;';:,;'.. .:,.',.   ..    .....'lO0o'.........    ...........
coccllc:::;,,,;:;;;;;::coooodddolcll,'.',. ':;;lo'  .,::c;cll:.  .;c;,:c. 'l:,';:..:;.;:c:;:::;.   ,:,',.            ...,dKXd.. .    .       .... ...
lolc;'.'''.,:c;;::ccllcllodoollol:'..';;c'  ':,:o;   ,c:c;lxoc.  .;c;';c,.'l:,'::.,l'.c:::,:::;.  .:;..'.   .         ..cOX0c........  .         .....
c::,'',clc;:ddoddolloollloooolll:,,'..,;c;. .:::dl..,c::l::ccc;';:cc:,;coc,',;,;:coo:,:;,,:c::;.  ':,'..   .          .cOX0l'.............  ..   .....
;;;,,coddoc;;:cldoooooooooollclc,',;' .,:c' .;c:ll,,lc;..';;:oddddxxxdc',,..,,';cddl;;,..;ooll:,..,,.....  .        .,d0Od:.............     ...    ..
,',;:ll:;ll;,;cdxddoollllllcccc:..,;;. ,:l:..;c,,',:cllc'.;:lxkOkxxxxxl.....,,':oxkd::,..:xkxxdlc:,.....  ..        ,xxl;'...............
..,,'.,;:ccoocoxxxxxdolllllc:::;..';:, .:c::ldl;;,:ddodxlcccoxOOOkkkxxl'':ccllclooddodo,.ckkxxdoc:;'....            .,.............''...  ...
:cc'.,;''::cddxOkllxkxooloolccc:;'';c:..;odxOOdc::lkxxxollc:lkO0Okkkxxl'.,ccc:::;;ccccc.'lxxkkdol:;,...              .  .................      .    ..
l;:codl,.,cdxdddlc:ccoddddddollc:;,,;'',;okkOOdc::loocloodl;okO00OOOxxd;,oxkkkkd:cxdodo;,oxkOkoll;''''...   ..         ........ ..   ....'..    ..   .
':oooccodoc;'.':ldxo::lodddddc:ccc:,;..,cdkOOOxodxkkkdk0O0xcdOO0K00Okkd::xOOOOkd:lkxxxx:;oxxxxdll:'.'....   ...     ... ........   ...    ....   ....
 ..':lddc,':ll:'';cdxxo::;:cclloooooo,.:odk000kx0K00kok0000OkO0KK0OOkxlcx0KKK0Kxlx0OOOOdcodollooc:,','...  ....   .........   ....     ....  .........
.:lcodxxccxOkdoolc,,;,...'cc;ll:ldooxc:oxkO00KOokXKKOdk0000Okk00Okkkxdlcx000OOOdoxOkkkOdcoxollolc:;;;'....  ...  ..... .. .        ......'....';;,;::'
dOO0KXNOxkxkxddxxdoodl,',;:,';;;;;:dkxkOO00000OodK000Ok00O0Ok0KXK0OOkOdlkK0000OxdkOkkxxocdxdoooc::;;,...... ...  .         .     ..........',,;col,...
K0OxOXKKXKKK0kkkdlc:cccodoc:llc;;:coxocoO00000OdxK00K0O00O0Oox0KK00Okkl:xK00OOOxoxOkkkkocdxxdolc;;;,'................ .......... ............'.....
0kdddOKKOxOOkO0Ol;,:l;;codloxkkxkkxdkd::d0KKK00ddK00K0O0K0K0clKXXK0OkOl;xXK0000kdk0OO00dldxkxdoc:;;,'..................',,'',,,'...,'....
00Kxd0KxooodxOOl;:dOlck0xlcx0KK0KKkxOxc:oOKK00KxdKK0K0k000K0clKXXKK0O0o;xK00000kxO0OO0Oolxkkxdol:;;,'.............'.';,..,,,,.':,..''....
0NXKKKKOxl:coxo;:dx:,d0x,.;,''';:;,;dx:,oOKK00KxxKKKXKOKXKXKllKXXKKK00d:kXK000KOkKK0000dlkkkxdlc:;;,'............,;,','.  .'....,.. ''..'.     ..... .
kXKKKKX0ocooc,.'::''l00c.','...''...lkdxOO0K00KxxXXKXKOKK0K0loKXXXKKK0xcxKK0000Ok0KOO0Oolkkxxdlc::;'''..........';:,.,;,,,''.,',:.  .   .,. ....','..'
XK0KKK0xcok;...,'..,xKk;,cl:;cloc;cldOkOK0KKKKXkxXNXNX0KXKXKodKXXXXXKKxckXKKKKKOOKK00K0olOOxxdlc:;,'''......'...,cl;.';:::,..'',:'.   ...,,',,,,;;;,,,
NKKXKKOkdkx........;OXx:oxdodxxdxkkxkOkOK0KXKKXkdKNKXKOKK0K0oxXXXXXXXKxlxKKKK00OkKKOO0OclOOxxolc::;'''......'..'oOk:..;cc;'...',c:'....,',:,,;;;:::;,,
XKXKkdxxdkd,.'''...;OXx:dkxdkOkxxOOkk0xkKKKKKKXkoKNXXX0KXKK0dxXNXXXXXKklkXKK00KOkKK00KOccOOxxol::;,'''... .''..;O0xc..;:cccc,.'',:'....;,;l;,;;;cc::,,
KKNNOk0Oxxx::lc'.'.;kXkcdOkxkOOxxO0OO0odKKKK0KXxl0NXXXO0X0K0xkXNXKXXXKkoxK00000OkKKOO0k:cOkxxdlc:;,'.'..  .','.,lll:..;:cldo:',;:c'...,l:co;,;;;ccc:;,
XXNNXKOkxkxcckd;,,.'xK0lo0OkkOkkxO0OO0llKKXXKKXx:ONXXX00XKKKkkXNNKXNXKOoxK0000KOkKKO00k;:Okxxdlc:;'.....  .',,.':cl:..;:cloo:,;:lc....;lcol,,;;:c:c:,'
XXNNX0OkxxxodOkc....cOKxlkOkxxkkxxOO0O::0KXXKKXd,xNKKX00K0KKkOXNNXXNXKOoxK00O00kkK0OO0x';kOkkdlc:;'.....   .,'.':col'.;;codo:,;::'....:cld:,,,;;:;:;,'
k0NNKddkxoddodxd,....oK0ookxlldlclllkk,;OKKKKKXo'xNKKKO0K000kOXNNXXNXKkoxK00000kk00OO0x',kkxxdlc:,'.....   .,,.':lod:';;clol,,:;,....,;:lc'''',;;;;,'.
K0KXX0OOkddoclooo:cdlcxK0o;;.',....,xd';k0KKKXKc.dXKKX0OK000O0XNNXXXXKkld00OO00kx00OO0d.'kkxxdlc:;''.....  .,,..:oxko,',;::,.,,'....'',::'.'''',''''..
NXKXXOkOkdooc;,,loclkd;o00o,..',;,,lOl.;x0KKKX0:.l000K0O000000XNNXXXXKkco00OO00kdk0OOOo.'xkxdolc:;,'.....  .,,'.:dk0k;.''........   .';'....''''''....
KX0kOkxdolc:cl:,co:....'lO0OkxdocclxO:';o0XKKXO, c0K0K0OK0000KXNXXXXX0k:cO0OOOOdokOkOkl..dkxddlc:;,'.....  .,,'.,dOKKo''.........  .,;...  ...........
:0X0OKX0Oxoolcol:cooool;':oodddolllkx,'';kK0KXx. :0K0K0O00000KXNXXXXX0k;:k0OOOkookkxxd; .okxddlc:;,'....   .','..lKXW0c...........';,.     .....   ...
 ,xKXKOkxoooldkkkOxlcll::odooodxdoc:,.';o0KKKKo. ;O00K0k000KKKXNXXXXX0x;;x0OOOkookkxkd, .lkxdolc:;'.....    .''. ,0WMWKo:,''....';,........   .....
. .:kK0xxkkkkOkoccc:ldOkdddolcc:;;;.  .;dKKKK0c  ,okO0OkO0O000XNXXXXK0x,,dOOOOklokkxxl'  :xxdolc:;'.....    ...  .oNMMMXkdolc:;'''...',;;;'.      .. .
.. ..ckKX0kdc::;:ok0Odoolll:,.  .;,,. .;dO00Kk, ;:'oO0Ox0000O0XXXXXXK0d''cxkkOOddOOOOo'. ;xxoollc;,...... ..      ,kWMMWX0kkkxdl:;;,......''...    ...
..',. .:dO0d;;lxOkdlclol;..  .,od:;c...;coxOOx::ol:dO0OxO0OOO0KXXKKKK0o.,c:cldOxdOOkkl,;.'dxoolc:;'........      ..:OWMMWNK0Okkkxl:,,;,..............
:xxxdc,..,::cxO0x::od:......;o0Xd';;,lxooc'':oddxxxkkOkkO0000OkO0kkkkkl';l:cclxxdkOkxl;c;.,c::;,''.....    .....  .;xNMMMMWNK0Okxkd:,,;;;..  .'''...
dxxkolo;',lxOOOl;dOo'..  .;clO0Od:,.,ddxx:':lolod:;:codxk0KXKOxddoloolloddddxdddddxdddooc:::;,.... .. ..   .....  .;OWMMWNWMWNK0kxxo;',;:;'...'.....
,;:,....:xOO0kl:kKo..   ,lc.:00Okl. 'dxxd,:kkddko.....;ddllxOo:clxkxdlodoloddooxdllc:;coc,;:;.     ....... .....  'dXMMMXKNMMWXK0xddc'.;::;'.
,..    'xO000o;xXk;.  .;lo,.:00OOko..cdx:'lxdokO:.lolxkkooox0: .,okxc,ld,.:xo::do'....:dc;:c:,''.. ........ .....;xXMMMWKKXNWMNKKkoxd;..::;,'.
......,dOO00OclKKd'.  ;ool..oOO000Kklclo,,dxddOk,'lloxOkcd0kx,.lxkkxccddodxxoloxo::lc.;oclc;:;''... .'..... ...;o0NWMWX00000NMWK0Olooc'.;:,,,'.      .
:.....lkOO00kcoK0d'  .lodo,'xOk0KKKXKkdc..,oddOo.,oldkOxlx00x''lxxkdccodc:ldolloo:,:;.,olc:;c:;,''. .'..... .:oOXNWWN0kxxxk0WMW0Okcloc,.:c;,,;.   ..',
dc,..;xOOO0KKddKKx;  ,oddxc'oOod0KKKKKKOxl;cccdc.;lcddxolxO0d.'oxxxdcldd' ,ooolodl:cc''odol:cc:;''. .......;okKXXXKkdoooodxKWWXkxoclcc;,cc;,;;'.',,'..
xdl,,:ok00KKKkd0XOl. ,oddxxc:xxllx0000KKKKKOoco:.. ..,llckkxl.;dxxxdcldo,.;oollloc:ld;.clod:::'..   ....,:oxkOOkkdl:::clld0NWNOolclocl;;ol:;;'...... .
NNXxoodO000KK0ddKXkc..lddxkxlcxxlccok0KKKKK00XKOdolc'.;c::lxc..,:cooccoo'.,lll:cl;',,..:o:;;;' ...'.,:cc:colc:::,''..,;:oOXNXkl::clcl;;ll:;:c,.   ....
NNNNNNKOOKKKXKK00XXOl';oddxkkdldxdl:coxOKXKKKK0O0XX0kkOxlcokl,'''.;c;':c. .:c,.;c.....'co:;cllc:looc::cc:;::,.........,oO00kl;'.,;cllcodolccc,....''.'
k0XNNNNK0OO00KKOkOO00d;:dxxkkkkdodxoc::cldk0KKXXKKkx0K00kkKKKkdO0Okooxxxl;oxxooloxxxdldkkkooxkxoccllc:::;,'..    ...'cxkkxo;'. .';:;,cooolll:.   .,'.,
.';cldk00OONNXKKKkoOXXOolodxkkkkxxdddolcc::cloxO0kx0XKK00K00OxkOOOOxOK00xlk00OOxdOOkkdokkkkxxkkxdcclc:,'....   ...';ldxxl:.....,;'.,:lollol:,.   .;.';
oc,''...::;d00OO0OOKKKXXOxxdodxOOkxxdxdddolc::::c:codkkOKKKK00K0O0kkOOO0xokKOkOOkOOkOOkkOOkkdddol;,,,'..........'':clc:;'.  .,::;'',;:ccccc,.....;;;,,
:xx::,..''.:KWWNNNXX0O0KXX0xddddddkkkxodxxxdolc:::,,;;;::ccllodddxxdxxk0koOKOxkkdxxdoolclcc:;;;;,',,''''''',''';;;;;,,.. ..,::;,;;;;;cllc,'...........
xkOo.   .,,:k0xlclodddkOoo0XK0xodxxdddkOOkddxxxddoc;;;;;;,;;,,,,;,,,,,,;,',;;;,,,,,,,'',,,,,,,,,',:::::::;;::;;,;;;'....,;;,,,',,;,,;lll;.    ........
xk0KOd:..;odo:,oKNNNWWWN0xx0XXKKkxoldkkkxdxkkkxodxxdxdolccc:;,,,,,,'''','.',,''''''''',,;;;;:clllldolooooc::c::;''..',:cc;'';:;;::cc:::;'    .,..,,..,
OkO0KK0Oxlc:,,;lOXNKOkkxxxx0KO0XXXK0kddodkkkOxookkkkxoxkkkkxdoooolcccc:c:,:c::c::cccllloodxdxxodkkkkdoxxxdoc:;;,,,:cc::;,''',,;:looo:..... .;;,,::'.'.
ONNXXNNKXNKkdkKK0OxokXNXNNWWNNX0kOOddOOOOkkkxoxkkkkxoxkkkOxldkkkkxoxkkkkdlxOkkkkdoxkkxkdoxkkkkdokOOOOxoxxdollcccllccc::::::::::::cc::'....';:,,;,,,'.,
Oxdk0OxOK0kO00Okko;,lONWWWXOdooodOOllk0KKKK0kkOkkkxoxOOOOkodOOOkOdokOkkOdoOK0kkOxoxkkkkkodkkkkkddkkkkxdxkOOOOko;;l:;;:::clooddo:,;;,;:;,,:c:;;:,'',,;;
l;.'d0xclOOllkkl;,:oxkOOko;lxOKXNNNNNNKkxkOOO0KKKK0OOkkkkdokOOOOkodOkkkOdoOK0OkkkodkkkkkdlxkxxxxxkOOO0OOO000O0OkO0OdollccdOOxl:'..................;:,.
,;' .OWKodXNkxKN0O0KXOlc;.:KWWNNNNXXN0l,;xKKOOOkO0XX0000OkkkkkkkxoxkkkkOdok00Okkkdoxxxxxxdxkkxk0KKK0Okkkkxld0XXKKK0KXNN0l,oOdlllc,..,,...'......'cl:,.

)";

#endif //BANNER_H
