//
// Created by Kyle on 28.03.25.
//

#ifndef GLOBALS_H
#define GLOBALS_H
#include <vector>

// Static lists for character creation
const std::vector<std::string> RACES = {
    "Demi Canadian",
    "Pivot Prodigy",
    "Foosball Philosopher",
    "Snack Sommelier",
    "Oddly Shaped Belgium",
    "Stand-up Desk Warrior",
    "Blockchain Bro",
    "Remote Work Ninja",
    "Growth Hacking Guru",
    "Venture Capital Whisperer",
    "Burnout Badge of Honor Wearer",
    "Kombucha Connoisseur",
    "Design Deity",
    "Tech Bro Translator",
    "Networking Ninja",
    "OKR Overlord",
    "Wellness Warrior",
    "Infinite Intern",
    "Legacy Engineer",
    "Culture Czar",
    "Founder's Bestie"
};

const std::vector<std::string> CLASSES = {
    // Scientist Roles (with Fusion Focus)
    "Fusion Energy Quantum Mechanics Maverick",
    "Plasma Containment and Cosmic Fusion Whisperer",
    "Tokamak Reactor Optimization Guru",
    "Nuclear Fusion Breakthrough Architect",
    "Stellarator System Dynamics Wizard",
    "Senior Splatter Researcher",
    "Fusioneer",


    // Engineering Roles
    "Extreme Thermal Management Ninja",
    "Superconducting Magnet Design Maestro",
    "Plasma-Material Interaction Alchemist",
    "Advanced Neutronics and Shielding Engineer",
    "Fusion Control Systems Virtuoso",

    // C-Level Roles
    "Chief Impossible Dreams Officer (CIDO)",
    "Visionary Disruption Czar",
    "Quantum Potential Maximization Executive",
    "Exponential Innovation Overlord",
    "Chief Radical Transformation Architect",

    // Random Roles
    "Professional Serendipity Orchestrator",
    "Chaos Theory Implementation Specialist",
    "Interdimensional Problem Solver",
    "Narrative Engineering Provocateur",
    "Unexpected Connections Choreographer"
};

const std::vector<std::string> equipment_list = {
    "Vintage Macbook Pro",
    "Emergency Coffee IV Drip",
    "Noise-Cancelling Headphones",
    "Ergonomic Standing Desk",
    "Bitcoin Mining Rig",
    "Quantum Computing Textbook",
    "Raspberry Pi Cluster",
    "VR Pitch Deck Simulator",
    "Startup Hoodie (Silicon Valley Edition)",
    "Mechanical Keyboard with RGB Backlighting",
    "Whiteboard Marker of Inspiration",
    "Debugging Energy Drink Stash",
    "Backup Charger Power Bank",
    "Laser Pointer for Epic Presentations",
    "Startup Motivational Poster",
    "Blockchain Certification",
    "AI Neural Network Schematics",
    "Emergency Pizza Delivery Card",
    "Noise-Cancelling Earpods",
    "Startup Equity Options Paperweight"
};

const std::vector<std::string> inventory_list = {
    "Quantum coffee beans",
    "Blockchain office plants",
    "Self-replicating Post-Its",
    "AI motivational posters",
    "VR meeting headsets",
    "Judgmental robot barista",
    "Smart whiteboard markers",
    "Biodegradable snack drones",
    "Spyware fidget spinners",
    "USB-C adapters",
    "Open-source pizza",
    "AR distraction glasses",
    "Crypto space heaters",
    "Tesla coil",
    "Dumb smart toaster",
    "Holographic guilt intern",
    "5G office chairs",
    "Disruptive pickles",
    "Autonomous stapler drones",
    "NFT mousepads",
    "Meme server cluster",
    "Passive-aggressive Slackbot",
    "3D-printed office pets",
    "Dusty Metaverse headset",
    "Dead unicorn plushies"
};
const std::vector<std::string> FUSION_STARTUPS = {
    "ELI-NP",
    "ELI Beamlines",
    "National Ignition Facility",
    "LLE Rochster",
    "Omega Machine",
    "FusionDAO",
    "Decentralized Stars",
    "FTX Fusion Partners",
    "Zap Energy",
    "Marble Fusion",
    "Radiant Nuclear",
    "Type One Energy",
    "PlasmaPunk Industries",
    "Kyoto Fusioneering",
    "Compact Fusion Systems",
    "Infinite Energy™ (YC S-2042)",
    "FusionHub",
    "Tokamak Energy",
    "Commonwealth Fusion Systems",
    "New Fusion",
    "Hotter Than Sun, Inc.",
    "Helical Fusion",
    "Theranos 2: Fusion Boogaloo",
    "First Light Fusion",
    "Princeton Fusion Systems",
    "Disruptive Tokamaks LLC",
    "Sun-in-a-Box Ventures",
    "HB11 Energy",
    "Zeno Power Systems",
    "Tinder for Nuclei ",
    "Carbon-Negative Neutrons",
    "Net Positive Fusion ",
    "Focused Energy",
    "Novatron Fusion Group",
    "OnlyFusions",
    "Renaissance Fusion",
    "Fusion-as-a-Service",
    "General Fusion",
    "Zero to Fusion Accelerator",
    "Avalanche Energy",
    "Nuclear Fusion Technologies",
    "UK Atomic Energy Authority",
    "Ultra Safe Nuclear Corporation",
    "LPPFusion",
    "X-Fusion",
    "SHINE Technologies",
    "FusionCoin Mining Collective",
    "Blockchain-Enabled Stellarators",
    "Key Fusion",
    "Kardashev Scale Pioneers",
    "EnsoFusion",
    "Energy Singularity",
    "ZETA Energy"
};

const std::vector<std::string> patent_list= {
    // Original absurdist spells
    "Infinite Scroll Summoning",
    "NFT Polymorph Spell",
    "Cloud Divination Engine",
    "Growth Hack Hex",
    "AI Love Potion",
    "Teleportation Tokenization",
    "Unicorn Valuation Charm",
    "Auto-Renewal Curse",
    "Viral Hex Algorithm",
    "Low-Code Necromancy",

    // Physics-flavored additions
    "Quantum Growth Hacking",
    "Entanglement Marketing",
    "Schrödinger’s MVP",
    "Dark Matter Analytics",
    "Tachyon SEO",
    "Zero-Point Energy SaaS",
    "Relativity Pivot",
    "Superposition A/B Testing",
    "Neutrino Data Mining",
    "Singularity Exit Strategy",
    "Wormhole UX",
    "Photon Engagement Boost",
    "Entropy Reversal Framework",
    "Higgs Boson Branding",
    "String Theory APIs",
    "Thermodynamic Hype Cycle",
    "Non-Newtonian KPIs",
    "Chaos Monetization",
    "Particle Accelerator Onboarding",
    "Quantum Tunneling Cookies",
    "Fusion Pitch Deck",
    "Anti-Gravity Churn",
    "Plasma Cloud Storage",
    "Electron Mindshare",
    "Bose-Einstein Viral Loop",
    "Hawking Radiation Ads",
    "Doppler Engagement",
    "M-Theory Unification",
    "Lepton Loyalty Program",
    "Spacetime Compression",
    "Quark-Gluon UX",
    "Helium Voice AI",
    "Pareto Principle Enchantment",
    "Fractal Growth Spell",
    "Eigenvalue Personalization",
    "Neural Network Alchemy",
    "Gravitational Wave Notifications",
    "Exponential Decay Pricing"
};

#endif //GLOBALS_H
